import Foundation

func source(_ path: String) throws -> String {
    try String(contentsOfFile: path, encoding: .utf8)
}

func assertContains(_ source: String, _ needle: String, _ message: String) {
    if !source.contains(needle) {
        fputs("Assertion failed: \(message). Missing: \(needle)\n", stderr)
        exit(1)
    }
}

func assertNotContains(_ source: String, _ needle: String, _ message: String) {
    if source.contains(needle) {
        fputs("Assertion failed: \(message). Unexpected: \(needle)\n", stderr)
        exit(1)
    }
}

func assertContainsInOrder(_ source: String, _ needles: [String], _ message: String) {
    var searchStart = source.startIndex
    for needle in needles {
        guard let range = source[searchStart...].range(of: needle) else {
            fputs("Assertion failed: \(message). Missing in order: \(needle)\n", stderr)
            exit(1)
        }
        searchStart = range.upperBound
    }
}

func slice(_ source: String, from start: String, to end: String) -> String {
    guard let startRange = source.range(of: start) else {
        fputs("Assertion failed: Could not find section start: \(start)\n", stderr)
        exit(1)
    }
    guard let endRange = source[startRange.upperBound...].range(of: end) else {
        fputs("Assertion failed: Could not find section end: \(end)\n", stderr)
        exit(1)
    }
    return String(source[startRange.lowerBound..<endRange.lowerBound])
}

let reuseSource = try source("NativeMac/NativeReuseViews.swift")
assertContains(reuseSource, "showStatisticsDashboard", "Bookshelf owns dashboard sub-state")
assertContains(reuseSource, "Label(\"Statistics\", systemImage: \"chart.xyaxis.line\")", "Bookshelf toolbar exposes an SF Symbols Statistics button")
assertContains(reuseSource, "Label(\"Bookshelf\", systemImage: \"books.vertical\")", "Dashboard toolbar exposes an SF Symbols Bookshelf return button")
assertContains(reuseSource, "StatisticsDashboardView(", "Bookshelf routes to the dashboard view")
assertContains(reuseSource, "shelves: viewModel.shelves", "Bookshelf passes shelf data into the statistics dashboard")

let dashboardSource = try source("Features/Bookshelf/StatisticsDashboardView.swift")
let dashboardStateSection = slice(dashboardSource, from: "struct StatisticsDashboardView", to: "var calendar")
let trendChartViewSection = slice(dashboardSource, from: "struct StatisticsTrendChartView", to: "private enum StatisticsDashboardPlaceholder")
assertContains(dashboardSource, "struct StatisticsDashboardView", "Dashboard view exists")
assertContains(dashboardSource, "private let statisticsDashboardSpacing: CGFloat = 16", "Dashboard uses compact top-level spacing")
assertContains(dashboardSource, "isLoadingSnapshot", "Dashboard tracks background statistics loading")
assertContains(dashboardSource, "snapshotLoadGeneration", "Dashboard ignores stale asynchronous snapshot loads")
assertContains(dashboardSource, "isInitialSnapshotLoading", "Dashboard distinguishes first-load placeholder rendering from normal empty data")
assertContains(dashboardSource, "statisticsInitialSnapshotLoadDelay", "Dashboard lets the initial UI present before scanning statistics files")
assertContains(dashboardSource, "loadingPlaceholderSnapshot", "Dashboard caches its first-loading placeholder snapshot instead of rebuilding it in body")
assertContains(dashboardSource, "displaySnapshot", "Dashboard renders from placeholder data while the first real snapshot loads")
assertContains(dashboardSource, "StatisticsDashboardPlaceholder.snapshot", "Dashboard prepares a local skeleton snapshot for first-load rendering")
assertContains(dashboardSource, "loadingDashboardPlaceholder(width:", "Dashboard renders the full UI immediately while the first snapshot loads")
assertContains(dashboardSource, ".redacted(reason: .placeholder)", "Dashboard hides placeholder values until real statistics arrive")
assertContains(dashboardSource, ".allowsHitTesting(false)", "Dashboard prevents placeholder controls from acting before real data is loaded")
assertContains(dashboardSource, "loadingStatusPill", "Dashboard shows a small nonblocking loading indicator over the skeleton")
assertContains(dashboardSource, "dashboardLayoutWithLoadingOverlay(width:", "Dashboard keeps current data visible during background reloads")
assertContains(dashboardSource, "StatisticsBookSnapshotInput", "Dashboard snapshots main-actor book metadata before background loading")
assertContains(dashboardSource, "cachedSnapshot(", "Dashboard applies cached statistics before the fresh background scan finishes")
assertContains(dashboardSource, "storeCachedSnapshot", "Dashboard persists refreshed statistics snapshots for faster re-entry")
assertContains(dashboardSource, "DispatchQueue.global(qos: .userInitiated).async", "Dashboard loads statistics sidecars off the main thread")
assertContains(dashboardSource, "DispatchQueue.main.async", "Dashboard applies loaded statistics back on the main thread")
assertContains(dashboardSource, "dashboardLayout(width:", "Dashboard uses a width-aware responsive layout")
assertContains(dashboardSource, "let contentWidth = max(proxy.size.width - 48, 0)", "Dashboard derives content width from the viewport")
assertContains(dashboardSource, "loadingDashboardPlaceholder(width: contentWidth)", "First-load skeleton receives the viewport content width")
assertContains(dashboardSource, "dashboardLayoutWithLoadingOverlay(width: contentWidth)", "Loaded dashboard receives the viewport content width")
assertContains(dashboardSource, ".frame(width: contentWidth, alignment: .topLeading)", "Dashboard scroll content fills the available viewport width")
assertContains(dashboardSource, "dashboardColumns(width: width)", "Dashboard keeps Trend above the responsive columns")
assertContains(dashboardSource, "fullWidthTrendSection", "Dashboard renders Trend as a full-width top row")
assertNotContains(dashboardSource, "rankingAndSpeedSection(width: width)", "Dashboard should use the middle column before adding lower rows")
assertContains(dashboardSource, "Range & Trend", "Trend section names the global range controls")
assertContains(dashboardSource, "Range filters all dashboard cards. Time Grain changes only the trend chart.", "Trend explains range and grain semantics")
assertContains(dashboardSource, "emptyDashboardState", "Empty statistics state keeps dashboard controls reachable")
assertContains(dashboardSource, "targetSettingsSection", "Dashboard exposes target controls in the main surface")
assertNotContains(dashboardSource, "loadingDashboardState", "Dashboard should not block first entry behind a standalone loading card")
assertContains(dashboardSource, "width >= 1_260", "Dashboard fills wide windows with three columns")
assertContains(dashboardSource, "HStack(alignment: .top", "Dashboard columns stay top-aligned while resizing")
assertContains(dashboardSource, "NativeSettingsStepperRow", "Dashboard reuses settings stepper rows for goal controls")
assertContains(dashboardSource, "speedSummarySection", "Dashboard includes speed insights inspired by external stats reports")
assertContains(dashboardSource, "Speed ignores reading samples under 1 minute.", "Dashboard explains speed filtering")
assertContains(dashboardSource, "bookRankingSection", "Dashboard includes book rankings inspired by external stats reports")
assertContains(dashboardSource, "StatisticsBookRankingMetric.allCases", "Book ranking exposes characters, duration, and speed")
assertContains(dashboardSource, "private let statisticsBookRankingLimit = 12", "Book ranking starts with a useful page of visible rows")
assertContains(dashboardSource, "@State private var visibleBookRankingLimit = statisticsBookRankingLimit", "Book ranking tracks its incrementally visible row count")
assertContains(dashboardSource, "limit: visibleBookRankingLimit + 1", "Book ranking requests one lookahead row to detect more results")
assertContains(dashboardSource, "candidateRows.prefix(visibleBookRankingLimit)", "Book ranking renders only the currently requested page count")
assertContains(dashboardSource, "Label(\"More Books\", systemImage: \"chevron.down\")", "Book ranking offers a native control to reveal another page")
assertContains(dashboardSource, "visibleBookRankingLimit += statisticsBookRankingLimit", "More Books reveals the next ranking page")
assertContains(dashboardSource, ".onChange(of: selectedRange)", "Changing the statistics range resets ranking pagination")
assertContains(dashboardSource, ".onChange(of: selectedBookRankingMetric)", "Changing the ranking metric resets ranking pagination")
assertContains(dashboardSource, "BookCover(book: book", "Book ranking and its detail panel show the book cover")
assertContains(dashboardSource, "selectedStatisticsBook", "Book ranking tracks the selected book")
assertContains(dashboardSource, ".sheet(item: $selectedStatisticsBook)", "Book ranking opens the selected book in a native sheet")
assertContains(dashboardSource, "StatisticsBookDetailPanel", "Dashboard includes per-book daily statistics details")
assertContains(dashboardSource, "Delete This Day", "Per-book statistics can delete a selected day")
assertContains(dashboardSource, "ReadingSessionLog.editing(", "Per-book statistics edit individual reading sessions")
assertContains(dashboardSource, "Delete This Session", "Per-book statistics can delete a single reading session")
assertContains(dashboardSource, "Delete All Statistics", "Per-book statistics can delete all recorded days")
assertContains(dashboardSource, "try StatisticsStorage.save(updated", "Statistics edits use the atomic session storage save path")
assertContains(dashboardSource, "NativeGlassCircleButton(systemName: \"xmark\"", "Per-book statistics uses the macOS 26 glass close control")
assertContains(dashboardSource, ".buttonStyle(.glassProminent)", "Per-book statistics uses a prominent macOS 26 glass save control")
assertContains(dashboardSource, ".buttonStyle(.glass)", "Per-book statistics uses macOS 26 glass destructive controls")
assertContains(dashboardSource, "Shelf Comparison", "Dashboard includes shelf comparison")
assertContains(dashboardSource, "shelfComparisonRows", "Dashboard calculates shelf comparison rows")
assertContains(dashboardSource, "Total Characters", "Shelf comparison exposes total character counts")
assertContains(dashboardSource, "Recorded Characters", "Shelf comparison exposes recorded character counts")
assertContains(dashboardSource, "Unshelved", "Shelf comparison includes books outside user shelves")
assertContains(dashboardSource, "Weekly Target Days", "Weekly target wording is explicit")
assertContains(dashboardSource, "selectedTrendGrain", "Trend chart separates display grain from selected range")
assertContains(dashboardSource, "StatisticsTrendGrain.allCases", "Trend grain selector exposes day, week, and month")
assertContains(dashboardSource, "Time Grain", "Trend labels the grain control explicitly")
assertContains(dashboardSource, "selectedTrendMetric", "Trend chart has a metric selector")
assertContains(dashboardSource, "StatisticsTrendMetric.allCases", "Trend metric selector exposes characters, duration, and speed")
assertContains(dashboardSource, "selectedTrendChartStyle", "Trend chart can switch between visual styles")
assertContains(dashboardSource, "StatisticsTrendChartStyle.allCases", "Trend style selector exposes bar and line views")
assertContains(dashboardSource, "StatisticsTrendChartView(", "Trend chart hover state is isolated in a child view")
assertNotContains(dashboardStateSection, "hoveredTrendPointID", "Dashboard parent does not own pointer hover state")
assertContains(trendChartViewSection, "@State private var hoveredTrendPointID", "Trend child view tracks the hovered point for custom data tooltips")
assertContains(trendChartViewSection, "hoveredTrendLocation", "Trend tooltip tracks the pointer location instead of pinning to a fixed chart edge")
assertContains(dashboardSource, "trendLineChart", "Trend chart renders a line view")
assertContains(dashboardSource, "if trendMetric != .speed, !current.isEmpty", "Speed line chart skips filtered samples without breaking valid points into isolated dots")
assertContains(dashboardSource, "trendLinePoint(", "Trend line chart derives plottable points separately from segment breaks")
assertContains(dashboardSource, "trendHoverOverlay", "Trend chart renders a hover overlay for both bar and line styles")
assertContains(dashboardSource, "trendChartHoverTrackingLayer", "Trend chart has a full plot hover layer")
assertContains(dashboardSource, ".onContinuousHover", "Trend chart updates tooltip position continuously as the pointer moves")
assertContains(dashboardSource, "statisticsTrendChartHeight", "Trend chart reserves enough plot height for hover detail cards")
assertContains(dashboardSource, "statisticsTrendChartHorizontalSafeInset", "Trend chart reserves horizontal safe space so edge labels are not clipped")
assertContains(dashboardSource, "statisticsTrendChartScrollIndicatorSafeInset", "Trend chart reserves bottom safe space so labels are not blocked by the horizontal scrollbar")
assertContains(dashboardSource, "statisticsTrendHoverDelayNanoseconds", "Trend hover appears after a short delay to avoid jitter")
assertContains(dashboardSource, "statisticsTrendHoverUpdateInterval", "Trend hover location updates are throttled")
assertContains(dashboardSource, "scheduleTrendHoverActivation()", "Trend hover activation is centralized instead of per-mark immediate updates")
assertContains(dashboardSource, "clearTrendHover()", "Trend hover state is cleared consistently")
assertContains(dashboardSource, "nearestTrendPoint(to:", "Trend hover maps pointer x-position to the nearest trend point")
assertContains(dashboardSource, "trendTooltipPosition(", "Trend tooltip position is computed near the pointer with bounds clamping")
assertContains(dashboardSource, "trendTooltipCard", "Trend chart hover state shows a data tooltip card")
assertContains(dashboardSource, "trendTooltipRow(\"Metric\"", "Trend tooltip shows the active metric value")
assertContains(dashboardSource, "point.bookBreakdown.prefix(3)", "Trend tooltip includes top book contributors like the reference report")
assertContains(dashboardSource, "opacity(0.001)", "Trend bars use nearly transparent hotspots so empty/short bars can still be hovered")
assertContains(dashboardSource, ".accessibilityLabel(Text(trendPointAccessibilityText", "Trend hover hotspots expose the same data to accessibility")
assertContains(dashboardSource, "GeometryReader", "Trend chart can fill available card width")
assertContains(dashboardSource, "trendContentWidth(availableWidth:", "Trend chart width fills short ranges and scrolls dense ranges")
assertContains(dashboardSource, "chartYAxis", "Trend chart includes a y-axis")
assertContains(dashboardSource, "trendBarWidth", "Trend chart keeps month labels readable with width-aware bars")
assertContains(trendChartViewSection, "private var trendEdgeInset", "Trend chart derives edge padding from the current label width")
assertContains(trendChartViewSection, "let usableWidth = max(contentWidth - trendEdgeInset * 2, 1)", "Trend chart positions first and last points inside the safe edge inset")
assertContains(trendChartViewSection, ".padding(.bottom, statisticsTrendChartScrollIndicatorSafeInset)", "Trend chart keeps x-axis labels above the horizontal scrollbar")
assertContains(dashboardSource, "ScrollView(.horizontal)", "Trend chart can scroll horizontally for dense ranges")
assertContains(dashboardSource, "Reading Calendar", "Dashboard includes calendar section")
assertContains(dashboardSource, "selectedCalendarDate", "Reading Calendar keeps its own selected date state")
assertContains(dashboardSource, "hasUserSelectedCalendarDate", "Reading Calendar distinguishes default latest date from manual clicks")
assertContains(dashboardSource, "latestCalendarDate", "Reading Calendar defaults to the latest available date")
assertContains(dashboardSource, "ScrollViewReader", "Reading Calendar can scroll to the selected/latest date")
assertContains(dashboardSource, "ScrollView(.horizontal, showsIndicators: true)", "Reading Calendar requests a draggable horizontal scroll bar")
assertContains(dashboardSource, ".scrollIndicators(.visible)", "Reading Calendar exposes a draggable horizontal scroll indicator")
assertContains(dashboardSource, "calendarSelectionFooter", "Reading Calendar shows the clicked date details")
assertContains(dashboardSource, "formattedFullDate(calendarSelectionDate)", "Reading Calendar displays the selected date")
assertContains(dashboardSource, "scrollHeatmap(to: calendarSelectionDate", "Reading Calendar scrolls to the selected/latest date")
assertContains(dashboardSource, "if !hasUserSelectedCalendarDate", "Reading Calendar resets default selection to the latest date on reload")
assertNotContains(dashboardSource, "By Book", "Dashboard should not include the removed By Book distribution module")
assertNotContains(dashboardSource, "distributionSection", "Dashboard should not render the removed By Book distribution module")
assertNotContains(dashboardSource, "distributionList", "Dashboard should not keep the removed By Book list")
assertNotContains(dashboardSource, "distributionRows", "Dashboard should not calculate the removed By Book distribution")
assertNotContains(dashboardSource, "selectedDistributionMetric", "Dashboard should not keep removed By Book metric state")
assertNotContains(dashboardSource, "StatisticsDistributionMetric", "Dashboard should not expose removed By Book metric controls")
assertNotContains(dashboardSource, "Share of Characters", "Dashboard should not keep By Book share labels")
assertNotContains(dashboardSource, "Share of Time", "Dashboard should not keep By Book share labels")
assertNotContains(dashboardSource, "selectedTab", "Selected range should not duplicate Trend/By Book switching")
assertNotContains(dashboardSource, "StatisticsDashboardRangeTab", "Selected range should not define duplicate range tabs")
assertNotContains(dashboardSource, "Label(\"Refresh\"", "Dashboard content should not keep the duplicate refresh button")
assertNotContains(dashboardSource, "Button(\"Bookshelf\")", "Dashboard content should not keep the duplicate Bookshelf button")
assertNotContains(dashboardSource, "title: \"Target Days\"", "Weekly target row should not use ambiguous wording")
assertNotContains(dashboardSource, "targetType: targetSettings.dailyTargetType", "Goal target type should not drive other dashboard cards")

let calendarSection = slice(dashboardSource, from: "var calendarSection", to: "private var heatmap")
assertNotContains(calendarSection, "NativeGlassSegmentedPicker", "Reading Calendar should not own the range picker")

let dashboardColumns = slice(dashboardSource, from: "func dashboardColumns", to: "@ViewBuilder\n    private var corruptStatisticsWarning")
assertContains(dashboardColumns, "let columnWidth = max((width - statisticsDashboardSpacing * 2) / 3, 260)", "Wide dashboard uses spacing-aware three-column math")
assertContains(dashboardColumns, "let doubleColumnWidth = columnWidth * 2 + statisticsDashboardSpacing", "Wide dashboard uses an explicit two-column cluster")
assertContains(dashboardColumns, ".frame(width: doubleColumnWidth", "Wide dashboard gives shelf comparison exactly two columns")
assertContains(dashboardColumns, "shelfComparisonSection", "Shelf comparison lives inside the wide responsive grid")
assertContainsInOrder(dashboardColumns, ["todaySection", "targetSettingsSection", "weekSection"], "Wide dashboard keeps the first column top-aligned without row-height gaps")
assertContainsInOrder(dashboardColumns, ["shelfComparisonSection", ".frame(width: doubleColumnWidth", "selectedRangeSection", "calendarSection", "speedSummarySection", "bookRankingSection"], "Wide dashboard keeps the right two columns packed upward under shelf comparison")
assertContainsInOrder(dashboardColumns, ["VStack(spacing: statisticsDashboardSpacing)", "shelfComparisonSection", "HStack(alignment: .top, spacing: statisticsDashboardSpacing)"], "Wide dashboard uses a right-side two-column stack instead of row-height layout")
assertContainsInOrder(dashboardColumns, ["else if width >= 840", "todaySection", "targetSettingsSection", "weekSection", "calendarSection", "shelfComparisonSection", "selectedRangeSection", "speedSummarySection", "bookRankingSection"], "Medium dashboard uses continuous column flow so later cards fill shorter-column gaps")
assertNotContains(dashboardColumns, "distributionSection", "Wide dashboard should not reserve a column for the removed By Book module")

let dashboardLayout = slice(dashboardSource, from: "func dashboardLayout", to: "private var fullWidthTrendSection")
assertNotContains(dashboardLayout, "shelfComparisonSection", "Shelf comparison should not force a separate full-width row")

let shelfComparisonSection = slice(dashboardSource, from: "var shelfComparisonSection", to: "private var trendSection")
assertContains(shelfComparisonSection, ".frame(minWidth: 660", "Shelf comparison table is compact enough for two dashboard columns")
assertContains(shelfComparisonSection, ".frame(minWidth: 640, minHeight: 96)", "Shelf comparison empty state keeps the compact footprint")

let shelfComparisonHelpers = slice(dashboardSource, from: "var shelfComparisonHeader", to: "private func goalRing")
assertContains(shelfComparisonHelpers, "HStack(spacing: 10)", "Shelf comparison columns use compact spacing")
assertContains(shelfComparisonHelpers, ".padding(.vertical, 7)", "Shelf comparison rows use compact vertical padding")

let trendSection = slice(dashboardSource, from: "var trendSection", to: "private var trendChart")
assertContains(trendSection, "selection: $selectedMode", "Trend owns the year/month/week/day range picker")
assertContains(trendSection, "StatisticsRangeMode.allCases", "Trend exposes all range modes")
assertContains(trendSection, "rangeModeText(mode)", "Trend reuses localized range labels")
assertContains(trendSection, "selection: $selectedTrendGrain", "Trend owns the day/week/month grain picker")
assertContains(trendSection, "trendGrainText(grain)", "Trend reuses localized grain labels")

let modelSource = try source("Features/Bookshelf/StatisticsDashboardModels.swift")
assertContains(modelSource, "struct StatisticsBookSnapshotInput: Sendable", "Statistics repository has a sendable background loading input")
assertContains(modelSource, "nonisolated static func loadSnapshot", "Statistics repository exposes a nonisolated background loading entry")
assertContains(modelSource, "StatisticsDashboardCachePayload", "Statistics repository persists a derived dashboard cache")
assertContains(modelSource, "StatisticsDashboardMemoryCache", "Statistics repository keeps an in-memory dashboard cache for fast re-entry")
assertContains(modelSource, "cachedSnapshot(", "Statistics repository can load cached dashboard snapshots")
assertContains(modelSource, "storeCachedSnapshot", "Statistics repository writes refreshed dashboard snapshots to cache")
assertContains(modelSource, "cacheSchemaVersion", "Statistics dashboard cache is versioned for compatibility")
assertContains(modelSource, "cacheKey(for:", "Statistics dashboard cache is keyed by the visible local book set")
assertContains(modelSource, "struct StatisticsTrendBookBreakdown", "Trend points carry book breakdown data for hover tooltips")
assertContains(modelSource, "let bookBreakdown: [StatisticsTrendBookBreakdown]", "Trend point model includes tooltip book contributors")
assertContains(modelSource, "trendBookBreakdown(days:", "Trend point calculation prepares top book contributors")
assertNotContains(modelSource, "StatisticsDistributionMetric", "Removed By Book module should not keep a distribution metric model")
assertNotContains(modelSource, "StatisticsDistributionRow", "Removed By Book module should not keep distribution rows")
assertNotContains(modelSource, "distributionRows(", "Removed By Book module should not keep distribution calculations")

let readerSource = try source("NativeMac/NativeReaderView.swift")
assertContains(readerSource, "prepareForExternalStatisticsMutation", "An open reader flushes its current statistics before an external edit")
assertContains(readerSource, "reloadStatisticsAfterExternalMutation", "An open reader reloads edited statistics instead of overwriting them later")

let visualTestSource = try source("script/test_statistics_dashboard_visual_utilization.swift")
assertContains(visualTestSource, "minimumImprovement", "Visual utilization test compares before and after screenshots")
assertContains(visualTestSource, "wide-right", "Visual utilization test can target wide right-side packing")
assertContains(visualTestSource, "medium-left", "Visual utilization test can target medium left-column packing")
assertContains(visualTestSource, "rowTwoRightSpan", "Visual utilization test inspects the second-row right-side dashboard area")
assertContains(visualTestSource, "rightLowerFollowup", "Visual utilization test catches row-height gaps below shelf comparison")
assertContains(visualTestSource, "mediumLeftFollowup", "Visual utilization test catches medium-width left column gaps")
assertContains(visualTestSource, "afterScore > beforeScore", "Visual utilization test requires the candidate layout to improve space use")

let settingsSource = try source("Features/Settings/StatisticsSettingsView.swift")
assertContains(settingsSource, "Autostart", "Settings keep statistics autostart controls")
assertNotContains(settingsSource, "Daily Goal", "Settings should not expose dashboard goal controls")
assertNotContains(settingsSource, "Weekly Goal", "Settings should not expose dashboard goal controls")
assertNotContains(settingsSource, "dailyStatisticsTargetType", "Settings should not edit dashboard target type")

print("statistics dashboard UI contract passed")
